### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by CatinhoCR** [rjcarneiro/angularjs-starter#12]
When I try to open the index.html from the dist folder (after running `gulp build`), it seems like it can't find any of the scripts or style files.

**Comment by rjcarneiro** [comment]
@CatinhoCR that's very weird... anything I can help you with?

**Comment by CatinhoCR** [comment]
@rjcarneiro 
Actually it's working pretty good.
Was working for about 12 hours so was burnt out and being dumb. My bad completely.
Thanks for the repo man, great work.

Quick question now that I have your attention, how would I go around removing the `web.config` file?
From what I understand that's a ASP.NET standard file, which I don't need.
If I remove it though the host won't allow me to access the compiled app.. Any ideas?

I am doing a quick front end app based on your seed, most angularJS (1.x) seeds don't work as expected or don't have enough documentation to fix issues, so again.. awesome job with this one man, thanks for sharing.

**Comment by rjcarneiro** [comment]
To remove the `web.config` file, you just delete the file and that's it.

> If I remove it though the host won't allow me to access the compiled app.. Any ideas?

That's very weird, can you show some logs and/or screenshot?
